#ifndef ATTACH_H
#include "Attach.h"
#endif

// Implementation of a code needed to generate PRBS sequences of various lengths
// R. Sheehan 12 - 2 - 2026


int main()
{
	// This is a PRBS sequence generated by a 7-bit linear feedback shift register (LFSR)
	// It's polynomial is x^{7} + x^{6} + 1
	// This means that the feedback taps are at bit-6 and bit-5 (assuming 0-indexed, MSB = bit-6)
	// A maximal-length PRBS-7 code has a period of 2^{7} - 1 = 127 bits long
	// The code below will generate that sequence

	uint8_t start = 0x02; // Initialise the sequence with value start =  = 2 in hex

	uint8_t a = start; // a is the 7-bit LFSR state, the mask 0x7f = 127 keeps the sequence 7-bits wide
	
	// Proceed to loop the generation of new bits until the sequence repeats itself
	int i; 
	for (i = 1;; i++) {
		// shift bit 6 to position 0, bit 5 to position 0, XOR the bits, mask newbit to 1-bit
		// this corresponds to the PRBS7 polynomial newbit = bit-6 \circleadd bit-5
		int newbit = (((a >> 6) ^ (a >> 5)) & 1);

		// shift the shift-register left by 1 (moving bits updward)
		// insert newbit into LSB
		// this forces result to 7-bits by masking with 0x7F
		// Update rule is 
		// b6 b5 b4 b3 b2 b1 b0   (old)
		// -> XOR = newbit
		// After shift: b5 b4 b3 b2 b1 b0 newbit
		a = ((a << 1) | newbit) & 0x7f;
		
		// prints each new value in the PRBS sequence
		printf("%x\n", a); 

		// The loop runs until the register returns to its starting value
		if (a == start) {
			printf("repetition period is %d\n", i);
			break;
		}

	}

	return 0;
}